FROM golang:alpine
ENV FYER_MONGO_ADDRESS mongo:27017
ENV FYER_PORT 4102
ENV FYER_PEER_REGISTER_PORT 4103
COPY ./ $GOPATH/src/github.com/Zumium/fyer/
RUN go install github.com/Zumium/fyer/center && rm -rf $GOPATH/src
CMD $GOPATH/bin/center
