// Code generated by protoc-gen-go.
// source: protos/peer/peer.proto
// DO NOT EDIT!

/*
Package peer is a generated protocol buffer package.

It is generated from these files:
	protos/peer/peer.proto

It has these top-level messages:
	DeployRequest
	DeployResponse
	FetchRequest
	FetchResponse
	FragInfoRequest
	FragInfoResponse
*/
package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployResponse_Status int32

const (
	DeployResponse_ERROR DeployResponse_Status = 0
	DeployResponse_OK    DeployResponse_Status = 1
)

var DeployResponse_Status_name = map[int32]string{
	0: "ERROR",
	1: "OK",
}
var DeployResponse_Status_value = map[string]int32{
	"ERROR": 0,
	"OK":    1,
}

func (x DeployResponse_Status) String() string {
	return proto.EnumName(DeployResponse_Status_name, int32(x))
}
func (DeployResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type FragInfoRequest_InfoType int32

const (
	FragInfoRequest_ALL  FragInfoRequest_InfoType = 0
	FragInfoRequest_FRAG FragInfoRequest_InfoType = 1
)

var FragInfoRequest_InfoType_name = map[int32]string{
	0: "ALL",
	1: "FRAG",
}
var FragInfoRequest_InfoType_value = map[string]int32{
	"ALL":  0,
	"FRAG": 1,
}

func (x FragInfoRequest_InfoType) String() string {
	return proto.EnumName(FragInfoRequest_InfoType_name, int32(x))
}
func (FragInfoRequest_InfoType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type FragInfoResponse_Status int32

const (
	FragInfoResponse_NOT_FOUND FragInfoResponse_Status = 0
	FragInfoResponse_OK        FragInfoResponse_Status = 1
	FragInfoResponse_ERROR     FragInfoResponse_Status = 2
)

var FragInfoResponse_Status_name = map[int32]string{
	0: "NOT_FOUND",
	1: "OK",
	2: "ERROR",
}
var FragInfoResponse_Status_value = map[string]int32{
	"NOT_FOUND": 0,
	"OK":        1,
	"ERROR":     2,
}

func (x FragInfoResponse_Status) String() string {
	return proto.EnumName(FragInfoResponse_Status_name, int32(x))
}
func (FragInfoResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type DeployRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FragIndex uint64 `protobuf:"varint,2,opt,name=frag_index,json=fragIndex" json:"frag_index,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeployRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployRequest) GetFragIndex() uint64 {
	if m != nil {
		return m.FragIndex
	}
	return 0
}

func (m *DeployRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeployResponse struct {
	Status DeployResponse_Status `protobuf:"varint,1,opt,name=status,enum=cn.zumium.fyer.peer.DeployResponse_Status" json:"status,omitempty"`
	Msg    string                `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *DeployResponse) Reset()                    { *m = DeployResponse{} }
func (m *DeployResponse) String() string            { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()               {}
func (*DeployResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeployResponse) GetStatus() DeployResponse_Status {
	if m != nil {
		return m.Status
	}
	return DeployResponse_ERROR
}

func (m *DeployResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type FetchRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FragIndex uint64 `protobuf:"varint,2,opt,name=frag_index,json=fragIndex" json:"frag_index,omitempty"`
}

func (m *FetchRequest) Reset()                    { *m = FetchRequest{} }
func (m *FetchRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()               {}
func (*FetchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FetchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FetchRequest) GetFragIndex() uint64 {
	if m != nil {
		return m.FragIndex
	}
	return 0
}

type FetchResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *FetchResponse) Reset()                    { *m = FetchResponse{} }
func (m *FetchResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchResponse) ProtoMessage()               {}
func (*FetchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FetchResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FragInfoRequest struct {
	Name      string                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Itype     FragInfoRequest_InfoType `protobuf:"varint,2,opt,name=itype,enum=cn.zumium.fyer.peer.FragInfoRequest_InfoType" json:"itype,omitempty"`
	FragIndex uint64                   `protobuf:"varint,3,opt,name=frag_index,json=fragIndex" json:"frag_index,omitempty"`
}

func (m *FragInfoRequest) Reset()                    { *m = FragInfoRequest{} }
func (m *FragInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*FragInfoRequest) ProtoMessage()               {}
func (*FragInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FragInfoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FragInfoRequest) GetItype() FragInfoRequest_InfoType {
	if m != nil {
		return m.Itype
	}
	return FragInfoRequest_ALL
}

func (m *FragInfoRequest) GetFragIndex() uint64 {
	if m != nil {
		return m.FragIndex
	}
	return 0
}

type FragInfoResponse struct {
	Status FragInfoResponse_Status            `protobuf:"varint,1,opt,name=status,enum=cn.zumium.fyer.peer.FragInfoResponse_Status" json:"status,omitempty"`
	Msg    string                             `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Infos  map[uint64]*FragInfoResponse_FInfo `protobuf:"bytes,3,rep,name=infos" json:"infos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *FragInfoResponse) Reset()                    { *m = FragInfoResponse{} }
func (m *FragInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*FragInfoResponse) ProtoMessage()               {}
func (*FragInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FragInfoResponse) GetStatus() FragInfoResponse_Status {
	if m != nil {
		return m.Status
	}
	return FragInfoResponse_NOT_FOUND
}

func (m *FragInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *FragInfoResponse) GetInfos() map[uint64]*FragInfoResponse_FInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type FragInfoResponse_FInfo struct {
	FragIndex uint64 `protobuf:"varint,1,opt,name=frag_index,json=fragIndex" json:"frag_index,omitempty"`
	Hash      []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *FragInfoResponse_FInfo) Reset()                    { *m = FragInfoResponse_FInfo{} }
func (m *FragInfoResponse_FInfo) String() string            { return proto.CompactTextString(m) }
func (*FragInfoResponse_FInfo) ProtoMessage()               {}
func (*FragInfoResponse_FInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *FragInfoResponse_FInfo) GetFragIndex() uint64 {
	if m != nil {
		return m.FragIndex
	}
	return 0
}

func (m *FragInfoResponse_FInfo) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*DeployRequest)(nil), "cn.zumium.fyer.peer.DeployRequest")
	proto.RegisterType((*DeployResponse)(nil), "cn.zumium.fyer.peer.DeployResponse")
	proto.RegisterType((*FetchRequest)(nil), "cn.zumium.fyer.peer.FetchRequest")
	proto.RegisterType((*FetchResponse)(nil), "cn.zumium.fyer.peer.FetchResponse")
	proto.RegisterType((*FragInfoRequest)(nil), "cn.zumium.fyer.peer.FragInfoRequest")
	proto.RegisterType((*FragInfoResponse)(nil), "cn.zumium.fyer.peer.FragInfoResponse")
	proto.RegisterType((*FragInfoResponse_FInfo)(nil), "cn.zumium.fyer.peer.FragInfoResponse.FInfo")
	proto.RegisterEnum("cn.zumium.fyer.peer.DeployResponse_Status", DeployResponse_Status_name, DeployResponse_Status_value)
	proto.RegisterEnum("cn.zumium.fyer.peer.FragInfoRequest_InfoType", FragInfoRequest_InfoType_name, FragInfoRequest_InfoType_value)
	proto.RegisterEnum("cn.zumium.fyer.peer.FragInfoResponse_Status", FragInfoResponse_Status_name, FragInfoResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FyerPeer service

type FyerPeerClient interface {
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	FragInfo(ctx context.Context, in *FragInfoRequest, opts ...grpc.CallOption) (*FragInfoResponse, error)
}

type fyerPeerClient struct {
	cc *grpc.ClientConn
}

func NewFyerPeerClient(cc *grpc.ClientConn) FyerPeerClient {
	return &fyerPeerClient{cc}
}

func (c *fyerPeerClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	out := new(DeployResponse)
	err := grpc.Invoke(ctx, "/cn.zumium.fyer.peer.FyerPeer/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fyerPeerClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	out := new(FetchResponse)
	err := grpc.Invoke(ctx, "/cn.zumium.fyer.peer.FyerPeer/Fetch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fyerPeerClient) FragInfo(ctx context.Context, in *FragInfoRequest, opts ...grpc.CallOption) (*FragInfoResponse, error) {
	out := new(FragInfoResponse)
	err := grpc.Invoke(ctx, "/cn.zumium.fyer.peer.FyerPeer/FragInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FyerPeer service

type FyerPeerServer interface {
	Deploy(context.Context, *DeployRequest) (*DeployResponse, error)
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	FragInfo(context.Context, *FragInfoRequest) (*FragInfoResponse, error)
}

func RegisterFyerPeerServer(s *grpc.Server, srv FyerPeerServer) {
	s.RegisterService(&_FyerPeer_serviceDesc, srv)
}

func _FyerPeer_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FyerPeerServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cn.zumium.fyer.peer.FyerPeer/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FyerPeerServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FyerPeer_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FyerPeerServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cn.zumium.fyer.peer.FyerPeer/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FyerPeerServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FyerPeer_FragInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FragInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FyerPeerServer).FragInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cn.zumium.fyer.peer.FyerPeer/FragInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FyerPeerServer).FragInfo(ctx, req.(*FragInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FyerPeer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cn.zumium.fyer.peer.FyerPeer",
	HandlerType: (*FyerPeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _FyerPeer_Deploy_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _FyerPeer_Fetch_Handler,
		},
		{
			MethodName: "FragInfo",
			Handler:    _FyerPeer_FragInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/peer/peer.proto",
}

func init() { proto.RegisterFile("protos/peer/peer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0xdd, 0x49, 0x9a, 0xd8, 0xdc, 0x6d, 0x6b, 0x18, 0x41, 0x4a, 0x64, 0xa1, 0xce, 0x2a, 0x94,
	0x55, 0xa3, 0xc4, 0x17, 0xd9, 0xb7, 0xae, 0xdd, 0x88, 0xb8, 0xb4, 0x3a, 0xae, 0x0a, 0xbe, 0x2c,
	0x71, 0xf7, 0x76, 0x5b, 0xdc, 0x26, 0x31, 0x93, 0x88, 0xf1, 0x4d, 0x04, 0xbf, 0xc5, 0xcf, 0x94,
	0x99, 0xa4, 0xb6, 0x86, 0x50, 0xc3, 0xbe, 0x84, 0x9b, 0x9b, 0x39, 0x67, 0xce, 0x99, 0x39, 0x37,
	0x70, 0x3b, 0x4e, 0xa2, 0x34, 0x12, 0x8f, 0x63, 0xc4, 0x44, 0x3d, 0x5c, 0xd5, 0xa0, 0xb7, 0xce,
	0x43, 0xf7, 0x7b, 0xb6, 0x5c, 0x64, 0x4b, 0x77, 0x96, 0xcb, 0x2e, 0x62, 0xc2, 0xde, 0x43, 0x77,
	0x8c, 0xf1, 0x55, 0x94, 0x73, 0xfc, 0x92, 0xa1, 0x48, 0x29, 0x85, 0x56, 0x18, 0x2c, 0xb1, 0x4f,
	0x06, 0x64, 0x68, 0x71, 0x55, 0xd3, 0x3d, 0x80, 0x59, 0x12, 0x5c, 0x9e, 0x2d, 0xc2, 0x0b, 0xfc,
	0xd6, 0xd7, 0x06, 0x64, 0xd8, 0xe2, 0x96, 0xec, 0xbc, 0x94, 0x0d, 0x09, 0xb9, 0x08, 0xd2, 0xa0,
	0xaf, 0x0f, 0xc8, 0xb0, 0xc3, 0x55, 0xcd, 0x7e, 0x12, 0xe8, 0xad, 0x88, 0x45, 0x1c, 0x85, 0x02,
	0xe9, 0x11, 0x98, 0x22, 0x0d, 0xd2, 0x4c, 0x28, 0xee, 0x9e, 0x77, 0xe0, 0xd6, 0x08, 0x72, 0xff,
	0x05, 0xb9, 0x6f, 0x15, 0x82, 0x97, 0x48, 0x6a, 0x83, 0xbe, 0x14, 0x97, 0x4a, 0x82, 0xc5, 0x65,
	0xc9, 0xee, 0x80, 0x59, 0xac, 0xa1, 0x16, 0x18, 0xc7, 0x9c, 0x4f, 0xb9, 0xbd, 0x43, 0x4d, 0xd0,
	0xa6, 0xaf, 0x6c, 0xc2, 0x46, 0xd0, 0xf1, 0x31, 0x3d, 0x9f, 0x5f, 0xdf, 0x1c, 0xdb, 0x87, 0x6e,
	0x49, 0x51, 0xda, 0x58, 0xb9, 0x25, 0x1b, 0x6e, 0x7f, 0x13, 0xb8, 0xe9, 0x2b, 0xc8, 0x2c, 0xda,
	0xb6, 0xd7, 0x73, 0x30, 0x16, 0x69, 0x1e, 0xa3, 0xda, 0xa6, 0xe7, 0x3d, 0xaa, 0x3d, 0x81, 0x0a,
	0x91, 0x2b, 0xeb, 0xd3, 0x3c, 0x46, 0x5e, 0x60, 0x2b, 0x82, 0xf5, 0xaa, 0xe0, 0x3d, 0x68, 0xaf,
	0x10, 0xf4, 0x06, 0xe8, 0xa3, 0x93, 0x13, 0x7b, 0x87, 0xb6, 0xa1, 0xe5, 0xf3, 0xd1, 0x0b, 0x9b,
	0xb0, 0x1f, 0x3a, 0xd8, 0xeb, 0x1d, 0x4a, 0x4f, 0xe3, 0xca, 0xd5, 0x3c, 0xfc, 0x8f, 0xb0, 0x86,
	0x97, 0x43, 0x7d, 0x30, 0x16, 0xe1, 0x2c, 0x12, 0x7d, 0x7d, 0xa0, 0x0f, 0x77, 0xbd, 0x27, 0xcd,
	0x68, 0xe5, 0x8b, 0x38, 0x0e, 0xd3, 0x24, 0xe7, 0x05, 0xdc, 0x39, 0x04, 0xc3, 0x97, 0xdd, 0x8a,
	0x77, 0x52, 0x93, 0xc4, 0x79, 0x20, 0xe6, 0x4a, 0x42, 0x87, 0xab, 0xda, 0x41, 0x80, 0x35, 0xa1,
	0xd4, 0xf8, 0x19, 0xf3, 0x12, 0x29, 0x4b, 0x3a, 0x02, 0xe3, 0x6b, 0x70, 0x95, 0x15, 0x77, 0xb2,
	0xeb, 0x3d, 0x68, 0xa6, 0x51, 0xc9, 0xe1, 0x05, 0xf2, 0x50, 0x7b, 0x46, 0xd8, 0xc1, 0xdf, 0x1c,
	0x76, 0xc1, 0x9a, 0x4c, 0x4f, 0xcf, 0xfc, 0xe9, 0xbb, 0xc9, 0x78, 0x9d, 0xc5, 0x75, 0x3c, 0x35,
	0xef, 0x97, 0x06, 0x6d, 0x3f, 0xc7, 0xe4, 0x35, 0x62, 0x42, 0xdf, 0x80, 0x59, 0x64, 0x9e, 0xb2,
	0xad, 0x03, 0xa1, 0xc2, 0xe0, 0xec, 0x37, 0x18, 0x1a, 0x3a, 0x01, 0x43, 0x65, 0x96, 0xde, 0xad,
	0x37, 0xb3, 0x31, 0x12, 0x0e, 0xdb, 0xb6, 0xa4, 0xe4, 0xfb, 0x00, 0xed, 0xd5, 0x01, 0xd0, 0x7b,
	0x4d, 0x32, 0xeb, 0xdc, 0x6f, 0x74, 0x8a, 0x47, 0xe6, 0xc7, 0x96, 0xfc, 0xf0, 0xc9, 0x54, 0x7f,
	0xa8, 0xa7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xb5, 0x20, 0x9b, 0xbb, 0x04, 0x00, 0x00,
}
