// Code generated by protoc-gen-go.
// source: protos/peer/peer.proto
// DO NOT EDIT!

/*
Package peer is a generated protocol buffer package.

It is generated from these files:
	protos/peer/peer.proto

It has these top-level messages:
	DeployRequest
	FetchRequest
	FetchResponse
	FragInfoRequest
	FragInfoResponse
*/
package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FragInfoRequest_InfoType int32

const (
	FragInfoRequest_ALL  FragInfoRequest_InfoType = 0
	FragInfoRequest_FRAG FragInfoRequest_InfoType = 1
)

var FragInfoRequest_InfoType_name = map[int32]string{
	0: "ALL",
	1: "FRAG",
}
var FragInfoRequest_InfoType_value = map[string]int32{
	"ALL":  0,
	"FRAG": 1,
}

func (x FragInfoRequest_InfoType) String() string {
	return proto.EnumName(FragInfoRequest_InfoType_name, int32(x))
}
func (FragInfoRequest_InfoType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type DeployRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FragIndex uint64 `protobuf:"varint,2,opt,name=frag_index,json=fragIndex" json:"frag_index,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeployRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployRequest) GetFragIndex() uint64 {
	if m != nil {
		return m.FragIndex
	}
	return 0
}

func (m *DeployRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FetchRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FragIndex uint64 `protobuf:"varint,2,opt,name=frag_index,json=fragIndex" json:"frag_index,omitempty"`
}

func (m *FetchRequest) Reset()                    { *m = FetchRequest{} }
func (m *FetchRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()               {}
func (*FetchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FetchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FetchRequest) GetFragIndex() uint64 {
	if m != nil {
		return m.FragIndex
	}
	return 0
}

type FetchResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *FetchResponse) Reset()                    { *m = FetchResponse{} }
func (m *FetchResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchResponse) ProtoMessage()               {}
func (*FetchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FetchResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FragInfoRequest struct {
	Name      string                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Itype     FragInfoRequest_InfoType `protobuf:"varint,2,opt,name=itype,enum=cn.zumium.fyer.peer.FragInfoRequest_InfoType" json:"itype,omitempty"`
	FragIndex uint64                   `protobuf:"varint,3,opt,name=frag_index,json=fragIndex" json:"frag_index,omitempty"`
}

func (m *FragInfoRequest) Reset()                    { *m = FragInfoRequest{} }
func (m *FragInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*FragInfoRequest) ProtoMessage()               {}
func (*FragInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FragInfoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FragInfoRequest) GetItype() FragInfoRequest_InfoType {
	if m != nil {
		return m.Itype
	}
	return FragInfoRequest_ALL
}

func (m *FragInfoRequest) GetFragIndex() uint64 {
	if m != nil {
		return m.FragIndex
	}
	return 0
}

type FragInfoResponse struct {
	Infos map[uint64]*FragInfoResponse_FInfo `protobuf:"bytes,3,rep,name=infos" json:"infos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *FragInfoResponse) Reset()                    { *m = FragInfoResponse{} }
func (m *FragInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*FragInfoResponse) ProtoMessage()               {}
func (*FragInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FragInfoResponse) GetInfos() map[uint64]*FragInfoResponse_FInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type FragInfoResponse_FInfo struct {
	FragIndex uint64 `protobuf:"varint,1,opt,name=frag_index,json=fragIndex" json:"frag_index,omitempty"`
	Hash      []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *FragInfoResponse_FInfo) Reset()                    { *m = FragInfoResponse_FInfo{} }
func (m *FragInfoResponse_FInfo) String() string            { return proto.CompactTextString(m) }
func (*FragInfoResponse_FInfo) ProtoMessage()               {}
func (*FragInfoResponse_FInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *FragInfoResponse_FInfo) GetFragIndex() uint64 {
	if m != nil {
		return m.FragIndex
	}
	return 0
}

func (m *FragInfoResponse_FInfo) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*DeployRequest)(nil), "cn.zumium.fyer.peer.DeployRequest")
	proto.RegisterType((*FetchRequest)(nil), "cn.zumium.fyer.peer.FetchRequest")
	proto.RegisterType((*FetchResponse)(nil), "cn.zumium.fyer.peer.FetchResponse")
	proto.RegisterType((*FragInfoRequest)(nil), "cn.zumium.fyer.peer.FragInfoRequest")
	proto.RegisterType((*FragInfoResponse)(nil), "cn.zumium.fyer.peer.FragInfoResponse")
	proto.RegisterType((*FragInfoResponse_FInfo)(nil), "cn.zumium.fyer.peer.FragInfoResponse.FInfo")
	proto.RegisterEnum("cn.zumium.fyer.peer.FragInfoRequest_InfoType", FragInfoRequest_InfoType_name, FragInfoRequest_InfoType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FyerPeer service

type FyerPeerClient interface {
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	FragInfo(ctx context.Context, in *FragInfoRequest, opts ...grpc.CallOption) (*FragInfoResponse, error)
}

type fyerPeerClient struct {
	cc *grpc.ClientConn
}

func NewFyerPeerClient(cc *grpc.ClientConn) FyerPeerClient {
	return &fyerPeerClient{cc}
}

func (c *fyerPeerClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/cn.zumium.fyer.peer.FyerPeer/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fyerPeerClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	out := new(FetchResponse)
	err := grpc.Invoke(ctx, "/cn.zumium.fyer.peer.FyerPeer/Fetch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fyerPeerClient) FragInfo(ctx context.Context, in *FragInfoRequest, opts ...grpc.CallOption) (*FragInfoResponse, error) {
	out := new(FragInfoResponse)
	err := grpc.Invoke(ctx, "/cn.zumium.fyer.peer.FyerPeer/FragInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FyerPeer service

type FyerPeerServer interface {
	Deploy(context.Context, *DeployRequest) (*google_protobuf.Empty, error)
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	FragInfo(context.Context, *FragInfoRequest) (*FragInfoResponse, error)
}

func RegisterFyerPeerServer(s *grpc.Server, srv FyerPeerServer) {
	s.RegisterService(&_FyerPeer_serviceDesc, srv)
}

func _FyerPeer_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FyerPeerServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cn.zumium.fyer.peer.FyerPeer/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FyerPeerServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FyerPeer_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FyerPeerServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cn.zumium.fyer.peer.FyerPeer/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FyerPeerServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FyerPeer_FragInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FragInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FyerPeerServer).FragInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cn.zumium.fyer.peer.FyerPeer/FragInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FyerPeerServer).FragInfo(ctx, req.(*FragInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FyerPeer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cn.zumium.fyer.peer.FyerPeer",
	HandlerType: (*FyerPeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _FyerPeer_Deploy_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _FyerPeer_Fetch_Handler,
		},
		{
			MethodName: "FragInfo",
			Handler:    _FyerPeer_FragInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/peer/peer.proto",
}

func init() { proto.RegisterFile("protos/peer/peer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0x75, 0x9a, 0xcd, 0xba, 0xbd, 0xdd, 0x6a, 0x18, 0xa1, 0x84, 0x48, 0x21, 0x46, 0x85, 0x80,
	0x38, 0x2b, 0xf1, 0x45, 0xfa, 0x16, 0x6d, 0x23, 0x42, 0x11, 0x19, 0x44, 0xc1, 0x17, 0x49, 0xdb,
	0x9b, 0xdd, 0xe0, 0x26, 0x13, 0xf3, 0x21, 0x8e, 0xbf, 0xc8, 0xbf, 0xe8, 0x83, 0x20, 0x33, 0x93,
	0xb5, 0x35, 0x84, 0xba, 0xf4, 0x25, 0x5c, 0x4e, 0xe6, 0x7c, 0xcc, 0x9d, 0x03, 0x07, 0x55, 0x2d,
	0x5a, 0xd1, 0x2c, 0x2a, 0xc4, 0x5a, 0x7f, 0x98, 0x06, 0xe8, 0xbd, 0xf3, 0x92, 0xfd, 0xe8, 0x8a,
	0xbc, 0x2b, 0x58, 0x26, 0x15, 0x8a, 0x58, 0x7b, 0xf7, 0x97, 0x42, 0x2c, 0xd7, 0xb8, 0xd0, 0x47,
	0xce, 0xba, 0x6c, 0x81, 0x45, 0xd5, 0x4a, 0xc3, 0x08, 0x3e, 0xc0, 0xfe, 0x31, 0x56, 0x6b, 0x21,
	0x39, 0x7e, 0xed, 0xb0, 0x69, 0x29, 0x85, 0x49, 0x99, 0x16, 0xe8, 0x12, 0x9f, 0x84, 0xbb, 0x5c,
	0xcf, 0xf4, 0x10, 0x20, 0xab, 0xd3, 0xe5, 0xe7, 0xbc, 0xbc, 0xc0, 0xef, 0xee, 0x8e, 0x4f, 0xc2,
	0x09, 0xdf, 0x55, 0xc8, 0x1b, 0x05, 0x28, 0xca, 0x45, 0xda, 0xa6, 0xae, 0xe5, 0x93, 0x70, 0xce,
	0xf5, 0x1c, 0xc4, 0x30, 0x4f, 0xb0, 0x3d, 0x5f, 0xdd, 0x5c, 0x36, 0x78, 0x08, 0xfb, 0xbd, 0x44,
	0x53, 0x89, 0xb2, 0xc1, 0xbf, 0x3e, 0xe4, 0x8a, 0xcf, 0x4f, 0x02, 0x77, 0x13, 0x4d, 0xc9, 0xc4,
	0x75, 0x5e, 0xaf, 0xc0, 0xce, 0x5b, 0x59, 0xa1, 0xb6, 0xb9, 0x13, 0x3d, 0x65, 0x23, 0x9b, 0x62,
	0x03, 0x21, 0xa6, 0xe6, 0xf7, 0xb2, 0x42, 0x6e, 0xb8, 0x83, 0xc0, 0xd6, 0x30, 0xf0, 0x21, 0xcc,
	0x36, 0x0c, 0x7a, 0x1b, 0xac, 0xf8, 0xf4, 0xd4, 0xb9, 0x45, 0x67, 0x30, 0x49, 0x78, 0xfc, 0xda,
	0x21, 0xc1, 0x6f, 0x02, 0xce, 0xa5, 0x43, 0x7f, 0xa7, 0x04, 0xec, 0xbc, 0xcc, 0x44, 0xe3, 0x5a,
	0xbe, 0x15, 0xee, 0x45, 0xcf, 0xfe, 0x93, 0xcb, 0xb0, 0x74, 0xb0, 0xe6, 0xa4, 0x6c, 0x6b, 0xc9,
	0x0d, 0xdd, 0x3b, 0x02, 0x3b, 0x51, 0xe8, 0x20, 0x23, 0x19, 0x79, 0xab, 0x55, 0xda, 0xac, 0xf4,
	0x1a, 0xe6, 0x5c, 0xcf, 0x1e, 0x02, 0x5c, 0x0a, 0x52, 0x07, 0xac, 0x2f, 0x28, 0x7b, 0xa6, 0x1a,
	0x69, 0x0c, 0xf6, 0xb7, 0x74, 0xdd, 0x99, 0xdd, 0xed, 0x45, 0x4f, 0xb6, 0xcb, 0xa8, 0xe3, 0x70,
	0xc3, 0x3c, 0xda, 0x79, 0x41, 0xa2, 0x5f, 0x04, 0x66, 0x89, 0xc4, 0xfa, 0x1d, 0x62, 0x4d, 0x8f,
	0x61, 0x6a, 0x7a, 0x47, 0x83, 0x51, 0xb9, 0x7f, 0x4a, 0xe9, 0x1d, 0x30, 0xd3, 0x61, 0xb6, 0xe9,
	0x30, 0x3b, 0x51, 0x1d, 0xa6, 0x6f, 0xc1, 0xd6, 0x15, 0xa1, 0x0f, 0xc6, 0x33, 0x5d, 0x69, 0xa0,
	0x17, 0x5c, 0x77, 0xa4, 0x7f, 0x8d, 0x8f, 0x30, 0xdb, 0xdc, 0x83, 0x3e, 0xda, 0xa6, 0x22, 0xde,
	0xe3, 0xad, 0x96, 0xf1, 0x72, 0xfa, 0x69, 0xa2, 0x7e, 0x9c, 0x4d, 0xf5, 0x05, 0x9e, 0xff, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xa9, 0xe7, 0x0e, 0x1f, 0xc1, 0x03, 0x00, 0x00,
}
