// Code generated by protoc-gen-go.
// source: protos/center/center.proto
// DO NOT EDIT!

/*
Package center is a generated protocol buffer package.

It is generated from these files:
	protos/center/center.proto

It has these top-level messages:
	RegisterRequest
	RegisterPeerRequest
	FileInfoRequest
	FileInfoResponse
	PeerInfoRequest
	PeerInfoResponse
*/
package center

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Size       uint64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Hash       []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	FragCount  uint64 `protobuf:"varint,4,opt,name=frag_count,json=fragCount" json:"frag_count,omitempty"`
	MerkleTree []byte `protobuf:"bytes,5,opt,name=merkle_tree,json=merkleTree,proto3" json:"merkle_tree,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RegisterRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RegisterRequest) GetFragCount() uint64 {
	if m != nil {
		return m.FragCount
	}
	return 0
}

func (m *RegisterRequest) GetMerkleTree() []byte {
	if m != nil {
		return m.MerkleTree
	}
	return nil
}

type RegisterPeerRequest struct {
	PeerId string `protobuf:"bytes,1,opt,name=peer_id,json=peerId" json:"peer_id,omitempty"`
}

func (m *RegisterPeerRequest) Reset()                    { *m = RegisterPeerRequest{} }
func (m *RegisterPeerRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterPeerRequest) ProtoMessage()               {}
func (*RegisterPeerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterPeerRequest) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type FileInfoRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *FileInfoRequest) Reset()                    { *m = FileInfoRequest{} }
func (m *FileInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*FileInfoRequest) ProtoMessage()               {}
func (*FileInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FileInfoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FileInfoResponse struct {
	Size       uint64 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	Hash       []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	FragCount  uint64 `protobuf:"varint,3,opt,name=frag_count,json=fragCount" json:"frag_count,omitempty"`
	MerkleTree []byte `protobuf:"bytes,4,opt,name=merkle_tree,json=merkleTree,proto3" json:"merkle_tree,omitempty"`
}

func (m *FileInfoResponse) Reset()                    { *m = FileInfoResponse{} }
func (m *FileInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*FileInfoResponse) ProtoMessage()               {}
func (*FileInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FileInfoResponse) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfoResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *FileInfoResponse) GetFragCount() uint64 {
	if m != nil {
		return m.FragCount
	}
	return 0
}

func (m *FileInfoResponse) GetMerkleTree() []byte {
	if m != nil {
		return m.MerkleTree
	}
	return nil
}

type PeerInfoRequest struct {
	PeerId string `protobuf:"bytes,1,opt,name=peer_id,json=peerId" json:"peer_id,omitempty"`
}

func (m *PeerInfoRequest) Reset()                    { *m = PeerInfoRequest{} }
func (m *PeerInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*PeerInfoRequest) ProtoMessage()               {}
func (*PeerInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PeerInfoRequest) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type PeerInfoResponse struct {
	// string username = 3;
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *PeerInfoResponse) Reset()                    { *m = PeerInfoResponse{} }
func (m *PeerInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*PeerInfoResponse) ProtoMessage()               {}
func (*PeerInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PeerInfoResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "cn.zumium.fyer.center.RegisterRequest")
	proto.RegisterType((*RegisterPeerRequest)(nil), "cn.zumium.fyer.center.RegisterPeerRequest")
	proto.RegisterType((*FileInfoRequest)(nil), "cn.zumium.fyer.center.FileInfoRequest")
	proto.RegisterType((*FileInfoResponse)(nil), "cn.zumium.fyer.center.FileInfoResponse")
	proto.RegisterType((*PeerInfoRequest)(nil), "cn.zumium.fyer.center.PeerInfoRequest")
	proto.RegisterType((*PeerInfoResponse)(nil), "cn.zumium.fyer.center.PeerInfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FyerCenter service

type FyerCenterClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// rpc RegisterPeer (RegisterPeerRequest) returns (google.protobuf.Empty);
	FileInfo(ctx context.Context, in *FileInfoRequest, opts ...grpc.CallOption) (*FileInfoResponse, error)
	PeerInfo(ctx context.Context, in *PeerInfoRequest, opts ...grpc.CallOption) (*PeerInfoResponse, error)
}

type fyerCenterClient struct {
	cc *grpc.ClientConn
}

func NewFyerCenterClient(cc *grpc.ClientConn) FyerCenterClient {
	return &fyerCenterClient{cc}
}

func (c *fyerCenterClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/cn.zumium.fyer.center.FyerCenter/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fyerCenterClient) FileInfo(ctx context.Context, in *FileInfoRequest, opts ...grpc.CallOption) (*FileInfoResponse, error) {
	out := new(FileInfoResponse)
	err := grpc.Invoke(ctx, "/cn.zumium.fyer.center.FyerCenter/FileInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fyerCenterClient) PeerInfo(ctx context.Context, in *PeerInfoRequest, opts ...grpc.CallOption) (*PeerInfoResponse, error) {
	out := new(PeerInfoResponse)
	err := grpc.Invoke(ctx, "/cn.zumium.fyer.center.FyerCenter/PeerInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FyerCenter service

type FyerCenterServer interface {
	Register(context.Context, *RegisterRequest) (*google_protobuf.Empty, error)
	// rpc RegisterPeer (RegisterPeerRequest) returns (google.protobuf.Empty);
	FileInfo(context.Context, *FileInfoRequest) (*FileInfoResponse, error)
	PeerInfo(context.Context, *PeerInfoRequest) (*PeerInfoResponse, error)
}

func RegisterFyerCenterServer(s *grpc.Server, srv FyerCenterServer) {
	s.RegisterService(&_FyerCenter_serviceDesc, srv)
}

func _FyerCenter_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FyerCenterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cn.zumium.fyer.center.FyerCenter/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FyerCenterServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FyerCenter_FileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FyerCenterServer).FileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cn.zumium.fyer.center.FyerCenter/FileInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FyerCenterServer).FileInfo(ctx, req.(*FileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FyerCenter_PeerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FyerCenterServer).PeerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cn.zumium.fyer.center.FyerCenter/PeerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FyerCenterServer).PeerInfo(ctx, req.(*PeerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FyerCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cn.zumium.fyer.center.FyerCenter",
	HandlerType: (*FyerCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _FyerCenter_Register_Handler,
		},
		{
			MethodName: "FileInfo",
			Handler:    _FyerCenter_FileInfo_Handler,
		},
		{
			MethodName: "PeerInfo",
			Handler:    _FyerCenter_PeerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/center/center.proto",
}

func init() { proto.RegisterFile("protos/center/center.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x49, 0x9b, 0xb7, 0x4d, 0xe7, 0x15, 0x5a, 0x56, 0xd4, 0x10, 0x11, 0x4b, 0x40, 0x2d,
	0x22, 0x5b, 0xd0, 0x6f, 0x60, 0xb1, 0x50, 0x4f, 0x12, 0x3c, 0xd9, 0x43, 0x49, 0x9b, 0x49, 0x1a,
	0x6c, 0xfe, 0xb8, 0xbb, 0x39, 0xb4, 0xdf, 0xc1, 0x8b, 0x9f, 0x58, 0x76, 0x93, 0x10, 0x89, 0x8d,
	0x3d, 0x65, 0xf2, 0xec, 0xb3, 0xc3, 0xf3, 0x9b, 0x1d, 0xb0, 0x52, 0x96, 0x88, 0x84, 0x8f, 0x57,
	0x18, 0x0b, 0x64, 0xc5, 0x87, 0x2a, 0x91, 0x9c, 0xac, 0x62, 0xba, 0xcb, 0xa2, 0x30, 0x8b, 0xa8,
	0xbf, 0x45, 0x46, 0xf3, 0x43, 0xeb, 0x3c, 0x48, 0x92, 0x60, 0x83, 0x63, 0x65, 0x5a, 0x66, 0xfe,
	0x18, 0xa3, 0x54, 0x6c, 0xf3, 0x3b, 0xf6, 0xa7, 0x06, 0x7d, 0x07, 0x83, 0x90, 0x0b, 0x64, 0x0e,
	0x7e, 0x64, 0xc8, 0x05, 0x21, 0xa0, 0xc7, 0x6e, 0x84, 0xa6, 0x36, 0xd4, 0x46, 0x3d, 0x47, 0xd5,
	0x52, 0xe3, 0xe1, 0x0e, 0xcd, 0xd6, 0x50, 0x1b, 0xe9, 0x8e, 0xaa, 0xa5, 0xb6, 0x76, 0xf9, 0xda,
	0x6c, 0x0f, 0xb5, 0xd1, 0x91, 0xa3, 0x6a, 0x72, 0x01, 0xe0, 0x33, 0x37, 0x58, 0xac, 0x92, 0x2c,
	0x16, 0xa6, 0xae, 0xdc, 0x3d, 0xa9, 0x4c, 0xa4, 0x40, 0x2e, 0xe1, 0x7f, 0x84, 0xec, 0x7d, 0x83,
	0x0b, 0xc1, 0x10, 0xcd, 0x7f, 0xea, 0x26, 0xe4, 0xd2, 0x2b, 0x43, 0xb4, 0x29, 0x1c, 0x97, 0x71,
	0x5e, 0xb0, 0x8a, 0x74, 0x06, 0xdd, 0x14, 0x91, 0x2d, 0x42, 0xaf, 0x48, 0xd5, 0x91, 0xbf, 0x33,
	0xcf, 0xbe, 0x82, 0xfe, 0x34, 0xdc, 0xe0, 0x2c, 0xf6, 0x93, 0x3f, 0xe2, 0xdb, 0x3b, 0x18, 0x54,
	0x36, 0x9e, 0x26, 0x31, 0xaf, 0x90, 0xb4, 0x3d, 0x48, 0xad, 0x46, 0xa4, 0xf6, 0x01, 0x24, 0xfd,
	0x17, 0xd2, 0x2d, 0xf4, 0x25, 0xca, 0xcf, 0x88, 0x8d, 0x38, 0x77, 0x30, 0xa8, 0xbc, 0x45, 0x4e,
	0x13, 0xba, 0xae, 0xe7, 0x31, 0xe4, 0xbc, 0x30, 0x97, 0xbf, 0xf7, 0x5f, 0x2d, 0x80, 0xe9, 0x16,
	0xd9, 0x44, 0x3d, 0x34, 0x79, 0x06, 0xa3, 0x9c, 0x1d, 0xb9, 0xa6, 0x7b, 0x97, 0x81, 0xd6, 0xde,
	0xda, 0x3a, 0xa5, 0xf9, 0x76, 0xd0, 0x72, 0x3b, 0xe8, 0x93, 0xdc, 0x0e, 0x32, 0x07, 0xa3, 0x1c,
	0x58, 0x63, 0xaf, 0xda, 0xe0, 0xad, 0x9b, 0x83, 0xbe, 0x82, 0x68, 0x0e, 0x46, 0x49, 0xd9, 0xd8,
	0xbc, 0x36, 0xb2, 0xc6, 0xe6, 0xf5, 0x71, 0x3d, 0x1a, 0x6f, 0x9d, 0xfc, 0x68, 0xd9, 0x51, 0x4c,
	0x0f, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x06, 0x30, 0x72, 0xe2, 0x34, 0x03, 0x00, 0x00,
}
